# general settings
appname: "Kratos"
twitter: "gem"
quotes_csv: "/home/christoph/Documenten/kratosproject/quotes/quotes.csv"
contest_types_csv: "/home/christoph/Documenten/kratosproject/quotes/contest_types.csv"
