# general settings
appname: "Kratos"
twitter: "gem"
quotes_csv: "/home/christoph/Documenten/kratosproject/setup/quotes.csv"
ctypes_csv: "/home/christoph/Documenten/kratosproject/setup/ctypes.csv"
test: "bier"
